from pathlib import Path
import sys

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.auth import is_admin_user
from src.config import CLASSES_PATH
from src.classes import (
    CLASS_COLUMNS,
    load_classes,
    make_class_import_template,
    normalize_classes,
    replace_classes_from_upload,
    save_classes,
    validate_classes,
)
from src.ui import page_header
from src.runtime import persist_runtime_state

user = st.session_state.get("auth_user", {})
if not is_admin_user(user):
    st.error("Admin access is required for this page.")
    st.stop()

page_header(
    "Classes",
    "Admin-only class master. Maintain the level, class/group name and whether it is active.",
)

st.info(
    "The class master has no year, class code or enrolment count. Teachers enter the number of pupils "
    "taking a diagnostic when they assign it. Pull-out groups and special teaching groups can be added here."
)

classes = load_classes(CLASSES_PATH)

st.subheader("Class master")
st.caption(
    "Add, edit or remove rows directly. Untick Active to hide a class from new diagnostics without deleting it."
)

if classes.empty:
    classes = pd.DataFrame(
        [{"Level": "P3", "Class_Name": "", "Active": True}],
        columns=CLASS_COLUMNS,
    )

edited = st.data_editor(
    classes,
    use_container_width=True,
    hide_index=True,
    num_rows="dynamic",
    column_order=CLASS_COLUMNS,
    column_config={
        "Level": st.column_config.SelectboxColumn("Level", options=["P3", "P4", "P5", "P6"], required=True),
        "Class_Name": st.column_config.TextColumn("Class / group name", help="Examples: Unity, Empathy, Pull-out Group A"),
        "Active": st.column_config.CheckboxColumn(
            "Active",
            help="Inactive classes remain in assignment history but do not appear for new diagnostics.",
        ),
    },
    key="class_master_editor",
)

edited = normalize_classes(edited)
errors = validate_classes(edited)
if errors:
    st.warning("Fix these before saving:\n\n" + "\n\n".join(f"• {e}" for e in errors))

if st.button("Save class master", type="primary", disabled=bool(errors), use_container_width=True):
    save_classes(edited, CLASSES_PATH)
    status = persist_runtime_state()
    st.success(f"Saved {len(edited)} class record{'s' if len(edited) != 1 else ''}.")
    if status.enabled and "failed" in status.message.lower():
        st.warning(status.message)
    st.rerun()

st.divider()
st.subheader("Mass update by CSV")
st.caption(
    "Upload the complete current class list. The uploaded file replaces the class master. "
    "Required columns: Level and Class_Name. Active is optional."
)

st.download_button(
    "Download class CSV template",
    make_class_import_template(),
    file_name="science_diagnostic_classes_template.csv",
    mime="text/csv",
    use_container_width=True,
)

uploaded = st.file_uploader("Upload class CSV", type=["csv"], key="class_csv_upload")
if uploaded is not None:
    try:
        incoming_raw = pd.read_csv(uploaded, dtype=str).fillna("")
        incoming = normalize_classes(incoming_raw)
        upload_errors = validate_classes(incoming)
        if incoming.empty:
            st.warning("The uploaded CSV does not contain any usable class rows.")
        elif upload_errors:
            st.error("The uploaded CSV needs attention:\n\n" + "\n\n".join(f"• {e}" for e in upload_errors))
        else:
            st.success(f"Ready to replace the class master with {len(incoming)} classes/groups.")
            st.dataframe(incoming, use_container_width=True, hide_index=True)
            confirm = st.checkbox(
                "I understand this replaces the current class master.",
                key="confirm_class_csv_replace",
            )
            if st.button("Apply CSV update", type="primary", disabled=not confirm, use_container_width=True):
                updated = replace_classes_from_upload(load_classes(CLASSES_PATH), incoming)
                save_classes(updated, CLASSES_PATH)
                status = persist_runtime_state()
                st.success("Class master updated from CSV.")
                if status.enabled and "failed" in status.message.lower():
                    st.warning(status.message)
                st.rerun()
    except Exception as exc:
        st.error(f"Could not read the class CSV: {type(exc).__name__}: {exc}")

st.caption(
    "Privacy note: the class master contains no pupil names or enrolment counts. "
    "A hidden internal identifier based only on Level + Class Name is generated by the app for Forms/response matching."
)
